var express = require('express');

var app = express()
, http = require('http')
, server = http.createServer(app)
, io = require('socket.io').listen(server);

server.listen(8080);

app.get('/', function (req, res) {
  res.sendfile(__dirname + '/index.html');
});

var connected_users = [];

io.sockets.on('connection', function (socket) {
 
 	socket.emit('welcome', { text: 'OH HAI! U R CONNECTED!' });
	io.sockets.emit('connected_users',{users : connected_users});

	//Listen to the add nickname event generated by the client
	socket.on('add_nickname',function(data,callback){
		

		if(connected_users.indexOf(data)>-1){
			callback(false);
		}else{
			callback(true);
			//add the user to the array     
                	connected_users.push(data);
                	//set the connected user so that he can be removed when disconnected
                	socket.nickname =  data;
                	console.log('Connected users : ' + connected_users);
			io.sockets.emit('connected_users',{users : connected_users});
		}

	});

	socket.on('send_message',function(data){
			
			io.sockets.emit('broadcast_messages',{
				user : socket.nickname, 
				message : data
				}
			);
		});

	socket.on('disconnect',function(){

		if(!socket.nickname) return true;

		if(connected_users.indexOf(socket.nickname) > -1){
		
			connected_users.splice(connected_users.indexOf(socket.nickname),1);

		}
		
		io.sockets.emit('connected_users',{users : connected_users});
		console.log('Connected users after disconnected : ' + connected_users);
	
		});
});



